import type { RouteRecordRaw } from 'vue-router';

import { permissoes } from '@/constants/permissoes';

const p = permissoes;

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    component: () => import('@/layouts/AuthLayout.vue'),
    children: [
      {
        path: '',
        name: 'login',
        component: () => import('@/pages/auth/LoginPage.vue'),
        meta: { publica: true },
      },
    ],
  },
  {
    path: '/cadastro',
    component: () => import('@/layouts/AuthLayout.vue'),
    children: [
      {
        path: '',
        name: 'cadastro',
        component: () => import('@/pages/auth/RegisterPage.vue'),
        meta: { publica: true },
      },
    ],
  },
  {
    path: '/primeiro-acesso',
    component: () => import('@/layouts/AuthLayout.vue'),
    children: [
      {
        path: '',
        name: 'primeiro-acesso',
        component: () => import('@/pages/auth/PrimeiroAcessoPage.vue'),
        meta: { publica: true },
      },
    ],
  },
  {
    path: '/',
    component: () => import('@/layouts/MainLayout.vue'),
    children: [
      {
        path: '',
        name: 'dashboard',
        component: () => import('@/pages/dashboard/DashboardPage.vue'),
        meta: { permissao: p.agenda.visualizar },
      },
      {
        path: 'unidades',
        name: 'unidades',
        component: () => import('@/pages/unidades/UnidadesListPage.vue'),
        meta: { permissao: p.unidades.visualizar },
      },
      {
        path: 'unidades/nova',
        name: 'unidades-nova',
        component: () => import('@/pages/unidades/UnidadeFormPage.vue'),
        meta: { permissao: p.unidades.criar },
      },
      {
        path: 'unidades/:id/editar',
        name: 'unidades-editar',
        component: () => import('@/pages/unidades/UnidadeFormPage.vue'),
        meta: { permissao: p.unidades.editar },
      },
      {
        path: 'unidades/:id/horario-funcionamento',
        name: 'unidades-horario-funcionamento',
        component: () => import('@/pages/unidades/UnidadeHorarioFuncionamentoPage.vue'),
        meta: { permissao: p.unidades.editar },
      },
      {
        path: 'pacientes',
        name: 'pacientes',
        component: () => import('@/pages/pacientes/PacientesListPage.vue'),
        meta: { permissao: p.pacientes.visualizar },
      },
      {
        path: 'pacientes/novo',
        name: 'pacientes-novo',
        component: () => import('@/pages/pacientes/PacienteFormPage.vue'),
        meta: { permissao: p.pacientes.criar },
      },
      {
        path: 'pacientes/:id/editar',
        name: 'pacientes-editar',
        component: () => import('@/pages/pacientes/PacienteFormPage.vue'),
        meta: { permissao: p.pacientes.editar },
      },
      {
        path: 'pacientes/:id/compras',
        name: 'pacientes-compras',
        component: () => import('@/pages/pacientes/PacienteComprasListPage.vue'),
        meta: { permissao: p.comprasPaciente.visualizar },
      },
      {
        path: 'pacientes/:id/compras/nova',
        name: 'pacientes-compras-nova',
        component: () => import('@/pages/pacientes/PacienteCompraFormPage.vue'),
        meta: { permissao: p.comprasPaciente.criar },
      },
      {
        path: 'compras',
        name: 'compras',
        component: () => import('@/pages/compras/ComprasListPage.vue'),
        meta: { permissao: p.comprasPaciente.visualizar },
      },
      {
        path: 'compras/nova',
        name: 'compras-nova',
        component: () => import('@/pages/pacientes/PacienteCompraFormPage.vue'),
        meta: { permissao: p.comprasPaciente.criar },
      },
      {
        path: 'pacotes',
        name: 'pacotes',
        component: () => import('@/pages/pacotes/PacotesListPage.vue'),
        meta: { permissao: p.pacotes.visualizar },
      },
      {
        path: 'pacotes/novo',
        name: 'pacotes-novo',
        component: () => import('@/pages/pacotes/PacoteFormPage.vue'),
        meta: { permissao: p.pacotes.criar },
      },
      {
        path: 'pacotes/:id/editar',
        name: 'pacotes-editar',
        component: () => import('@/pages/pacotes/PacoteFormPage.vue'),
        meta: { permissao: p.pacotes.editar },
      },
      {
        path: 'aplicacoes-paciente',
        name: 'aplicacoes-paciente',
        component: () => import('@/pages/aplicacoes-paciente/AplicacoesPacienteListPage.vue'),
        meta: { permissao: p.aplicacoes.visualizar },
      },
      {
        path: 'aplicacoes-paciente/nova',
        name: 'aplicacoes-paciente-nova',
        component: () => import('@/pages/aplicacoes-paciente/AplicacaoPacienteFormPage.vue'),
        meta: { permissao: p.aplicacoes.criar },
      },
      {
        path: 'aplicacoes-paciente/:id/editar',
        name: 'aplicacoes-paciente-editar',
        component: () => import('@/pages/aplicacoes-paciente/AplicacaoPacienteFormPage.vue'),
        meta: { permissao: p.aplicacoes.editar },
      },
      {
        path: 'procedimentos',
        name: 'procedimentos',
        component: () => import('@/pages/procedimentos/ProcedimentosListPage.vue'),
        meta: { permissao: p.procedimentos.visualizar },
      },
      {
        path: 'procedimentos/novo',
        name: 'procedimentos-novo',
        component: () => import('@/pages/procedimentos/ProcedimentoFormPage.vue'),
        meta: { permissao: p.procedimentos.criar },
      },
      {
        path: 'procedimentos/:id/editar',
        name: 'procedimentos-editar',
        component: () => import('@/pages/procedimentos/ProcedimentoFormPage.vue'),
        meta: { permissao: p.procedimentos.editar },
      },
      {
        path: 'sintomas',
        name: 'sintomas',
        component: () => import('@/pages/sintomas/SintomasListPage.vue'),
        meta: { permissao: p.sintomas.visualizar },
      },
      {
        path: 'sintomas/novo',
        name: 'sintomas-novo',
        component: () => import('@/pages/sintomas/SintomaFormPage.vue'),
        meta: { permissao: p.sintomas.criar },
      },
      {
        path: 'sintomas/:id/editar',
        name: 'sintomas-editar',
        component: () => import('@/pages/sintomas/SintomaFormPage.vue'),
        meta: { permissao: p.sintomas.editar },
      },
      {
        path: 'funcionarios',
        name: 'funcionarios',
        component: () => import('@/pages/funcionarios/FuncionariosListPage.vue'),
        meta: { permissao: p.funcionarios.visualizar },
      },
      {
        path: 'funcionarios/novo',
        name: 'funcionarios-novo',
        component: () => import('@/pages/funcionarios/FuncionarioFormPage.vue'),
        meta: { permissao: p.funcionarios.criar },
      },
      {
        path: 'funcionarios/:id/editar',
        name: 'funcionarios-editar',
        component: () => import('@/pages/funcionarios/FuncionarioFormPage.vue'),
        meta: { permissao: p.funcionarios.editar },
      },
      {
        path: 'funcionarios/:id/permissoes',
        name: 'funcionarios-permissoes',
        component: () => import('@/pages/funcionarios/FuncionarioPermissoesPage.vue'),
        meta: { permissao: p.funcionarios.editar },
      },
      {
        path: 'cargos',
        name: 'cargos',
        component: () => import('@/pages/cargos/CargosListPage.vue'),
        meta: { permissao: p.cargos.visualizar },
      },
      {
        path: 'cargos/novo',
        name: 'cargos-novo',
        component: () => import('@/pages/cargos/CargoFormPage.vue'),
        meta: { permissao: p.cargos.criar },
      },
      {
        path: 'cargos/:id/editar',
        name: 'cargos-editar',
        component: () => import('@/pages/cargos/CargoFormPage.vue'),
        meta: { permissao: p.cargos.editar },
      },
      {
        path: 'produtos',
        name: 'produtos',
        component: () => import('@/pages/produtos/ProdutosListPage.vue'),
        meta: { permissao: p.produtos.visualizar },
      },
      {
        path: 'produtos/novo',
        name: 'produtos-novo',
        component: () => import('@/pages/produtos/ProdutoFormPage.vue'),
        meta: { permissao: p.produtos.criar },
      },
      {
        path: 'produtos/:id/editar',
        name: 'produtos-editar',
        component: () => import('@/pages/produtos/ProdutoFormPage.vue'),
        meta: { permissao: p.produtos.editar },
      },
      {
        path: 'tipos-produto',
        name: 'tipos-produto',
        component: () => import('@/pages/tipos-produto/TiposProdutoListPage.vue'),
        meta: { permissao: p.tiposProduto.visualizar },
      },
      {
        path: 'tipos-produto/novo',
        name: 'tipos-produto-novo',
        component: () => import('@/pages/tipos-produto/TipoProdutoFormPage.vue'),
        meta: { permissao: p.tiposProduto.criar },
      },
      {
        path: 'tipos-produto/:id/editar',
        name: 'tipos-produto-editar',
        component: () => import('@/pages/tipos-produto/TipoProdutoFormPage.vue'),
        meta: { permissao: p.tiposProduto.editar },
      },
      {
        path: 'unidades-medida',
        name: 'unidades-medida',
        component: () => import('@/pages/unidades-medida/UnidadesMedidaListPage.vue'),
        meta: { permissao: p.unidadesMedida.visualizar },
      },
      {
        path: 'unidades-medida/nova',
        name: 'unidades-medida-nova',
        component: () => import('@/pages/unidades-medida/UnidadeMedidaFormPage.vue'),
        meta: { permissao: p.unidadesMedida.criar },
      },
      {
        path: 'unidades-medida/:id/editar',
        name: 'unidades-medida-editar',
        component: () => import('@/pages/unidades-medida/UnidadeMedidaFormPage.vue'),
        meta: { permissao: p.unidadesMedida.editar },
      },
      {
        path: 'saldos-estoque',
        name: 'saldos-estoque',
        component: () => import('@/pages/estoque/SaldosEstoqueListPage.vue'),
        meta: { permissao: p.estoque.visualizar },
      },
      {
        path: 'movimentacoes-estoque',
        name: 'movimentacoes-estoque',
        component: () => import('@/pages/estoque/MovimentacoesEstoqueListPage.vue'),
        meta: { permissao: p.estoque.visualizar },
      },
      {
        path: 'movimentacoes-estoque/entrada',
        name: 'movimentacoes-estoque-entrada',
        component: () => import('@/pages/estoque/MovimentacaoEstoqueFormPage.vue'),
        meta: { permissao: p.estoque.movimentar },
      },
      {
        path: 'movimentacoes-estoque/saida',
        name: 'movimentacoes-estoque-saida',
        component: () => import('@/pages/estoque/MovimentacaoEstoqueFormPage.vue'),
        meta: { permissao: p.estoque.movimentar },
      },
      {
        path: 'fornecedores',
        name: 'fornecedores',
        component: () => import('@/pages/fornecedores/FornecedoresListPage.vue'),
        meta: { permissao: p.fornecedores.visualizar },
      },
      {
        path: 'fornecedores/novo',
        name: 'fornecedores-novo',
        component: () => import('@/pages/fornecedores/FornecedorFormPage.vue'),
        meta: { permissao: p.fornecedores.criar },
      },
      {
        path: 'fornecedores/:id/editar',
        name: 'fornecedores-editar',
        component: () => import('@/pages/fornecedores/FornecedorFormPage.vue'),
        meta: { permissao: p.fornecedores.editar },
      },
      {
        path: 'pedidos-fornecedor',
        name: 'pedidos-fornecedor',
        component: () => import('@/pages/pedidos-fornecedor/PedidosFornecedorListPage.vue'),
        meta: { permissao: p.pedidosFornecedor.visualizar },
      },
      {
        path: 'pedidos-fornecedor/novo',
        name: 'pedidos-fornecedor-novo',
        component: () => import('@/pages/pedidos-fornecedor/PedidoFornecedorFormPage.vue'),
        meta: { permissao: p.pedidosFornecedor.criar },
      },
      {
        path: 'pedidos-fornecedor/:id/editar',
        name: 'pedidos-fornecedor-editar',
        component: () => import('@/pages/pedidos-fornecedor/PedidoFornecedorFormPage.vue'),
        meta: { permissao: p.pedidosFornecedor.editar },
      },
      {
        path: 'empresas',
        name: 'empresas',
        component: () => import('@/pages/empresas/EmpresasListPage.vue'),
        meta: { permissao: p.empresas.visualizar },
      },
      {
        path: 'empresas/nova',
        name: 'empresas-nova',
        component: () => import('@/pages/empresas/EmpresaFormPage.vue'),
        meta: { permissao: p.empresas.criar },
      },
      {
        path: 'empresas/atual',
        name: 'empresas-atual',
        component: () => import('@/pages/empresas/EmpresaConfigPage.vue'),
        meta: { permissao: p.empresas.editar },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'not-found',
    component: () => import('@/pages/ErrorNotFound.vue'),
    meta: { publica: true },
  },
];
